### ISSUE TITLE
Not passing safety test for me.

### ISSUE THREAD

**Issue by gautam-jha** [SuperiorOS-Devices/device_xiaomi_tulip#1]
Let me know if this is my device issue.

I am new with superior os. But when I used havoc then the Netflix was available in Google play. Even when I rooted phone with magisk.

In Superior os. There was no Netflix in playstore. Rooted it with magisk to check if this passes safety check but ctsProfile is false.

I cleaned flash ROM with OrangeFox.
![Screenshot_20200708-105928618](https://user-images.githubusercontent.com/16630278/86881132-66b28d00-c10b-11ea-96c2-753507ef811f.jpg)

**Comment by AtlanPrime** [comment]
meh.
